name: RSpec Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips-tools postgresql-client libpq-dev

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.1'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Yarn
        run: npm install -g yarn

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
        run: bin/rails db:setup && bin/rails spec
